# Display

VIRTUAL_WIDTH = 800
VIRTUAL_HEIGHT = 600
MARGIN = 25

WINDOW_WIDTH = VIRTUAL_WIDTH * 2
WINDOW_HEIGHT = VIRTUAL_HEIGHT * 2

FPS = 60

# Objects

TILE_SIZE = 32
TILE_ROW_COUNT = 9
TILE_COLUMN_COUNT = 12
BOARD_SIZE = 8
BOARD_OFFSET = (400, 100)