# SETTINGS

## DISPLAY

WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720

VIRTUAL_WIDTH = 512
VIRTUAL_HEIGHT = 288

FPS = 60

## IMAGE PATHS

BIRD_IMAGE = "wk1/assets/bird.png"
PIPE_IMAGE = "wk1/assets/pipe.png"
BACKGROUND_IMAGE = "wk1/assets/background.png"
GROUND_IMAGE = "wk1/assets/ground.png"

## PARALLAX

BACKGROUND_LOOPING_X = 413
BACKGROUND_SCROLL_SPEED = 30
GROUND_SCROLL_SPEED = 60

## GAMEPLAY

GRAVITY = 20
PIPE_SPAWN_INTERVAL = 2
PIPE_GAP = 90
PIPE_HEIGHT = 288
PIPE_SCROLL_SPEED = -60
PIPE_WIDTH = 70